service: blogbot

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action: 
            - 's3:ListBucket'
          Resource: !GetAtt blogBucket.Arn
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource: !Join ["", [!GetAtt blogBucket.Arn, "/*"]]
        - Effect: 'Allow'
          Action:
            - 'ssm:GetParameter'
          Resource: 'arn:aws:ssm:us-east-2:329082876876:parameter/git-lambda'

functions:
  writer:
    handler: handler.writer
    timeout: 30
    environment:
      BUCKET_NAME: !Ref blogBucket
      MY_REGION: ${aws:region}
  publisher:
    handler: publisher.publisher
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:553035198032:layer:git-lambda2:8
    # package:
    #   individually: true
    environment:
      BUCKET_NAME: !Ref blogBucket
      MY_REGION: ${aws:region}
      GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa'

resources:
  Resources:
    blogBucket:
      Type: AWS::S3::Bucket
      # Properties:
      #   BucketName: !Join
      #     - "-"
      #     - - "blogbot-bucket"
      #       - !Ref AWS::Region
  Outputs:
    BlogBucket:
      Description: The blog bucket name
      Value: !Ref blogBucket

plugins:
  - serverless-python-requirements
